### ISSUE TITLE
Mapzen discontinued Borders on October 14th, 2016

### ISSUE THREAD

**Issue by michael-jacques** [Mapotempo/geocoder-api#2]
The README in ./poly points to https://mapzen.com/data/borders/, which is discontinued.

This seems to be the current iteration: https://whosonfirst.mapzen.com/spelunker/

**Comment by frodrigo** [comment]
whosonfirst not seem to be a good replacement, as Mapzen will be totally discontinued at the end of the month.

**Comment by michael-jacques** [comment]
Ah i see i had no idea
