### ISSUE TITLE
Cant start this as daemon in production mode..

### ISSUE THREAD

**Issue by ghost** [Mapotempo/geocoder-api#3]
It starts in dev mode by default even if i say APP_ENV=production .. 
and my mapotempo-web localhost returns geocode failed

**Comment by frodrigo** [comment]
About the APP_ENV it's a know issue.

Are you using a working addok instance (private local instance or public remote) ?

**Comment by johnGarcia123** [comment]
am using here, local

**Comment by johnGarcia123** [comment]
bundle exec puma -d tcp://yourip -p 8558 -d & succesfully starts it as daemon, but my mapotempo-web still says geocoding failed

**Comment by meloBerati** [comment]
geocoding on geocoder-api frontend is done well, but it cant be accesed from mapotempo-web

**Comment by frodrigo** [comment]
You shoul overwrite this in your config file:
```
    Mapotempo::Application.config.geocode_geocoder = GeocodeAddokWrapper.new('https://geocode.mapotempo.com/0.1', 'secret_api_key')
```

**Comment by johnGarcia123** [comment]
it geocodes only single destinations.. when i import  destinations list they wont get geocoded..

**Comment by meloBerati** [comment]
yes, same here.. massive import is not geocoded

**Comment by frodrigo** [comment]
Mass import is done by delayed_job
https://github.com/Mapotempo/mapotempo-web#running
Do you start delayed_job?
