### ISSUE TITLE
Error building with docker

### ISSUE THREAD

**Issue by ghost** [Mapotempo/geocoder-api#4]
ERROR: Service 'wrapper' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y git build-essential zlib1g-dev gdal-bin             zlib1g libsqlite3-mod-spatialite libsqlite3-dev             libspatialite-dev &&     cd /srv/app &&     bundle install --full-index --without test development &&         chown -R www-data:www-data . &&         apt-get remove -y git build-essential zlib1g-dev gdal-bin             libsqlite3-dev libspatialite-dev &&     apt-get autoremove -y &&     apt-get clean &&     echo -n > /var/lib/apt/extended_states &&     rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*' returned a non-zero code: 18

**Comment by frodrigo** [comment]
It's a reproducible issues ?
Try build with `--no-cache`option.

**Comment by johnGarcia123** [comment]
same error  after bulding with --no-cache  
ERROR: Service 'wrapper' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y git build-essential zlib1g-dev gdal-bin             zlib1g libsqlite3-mod-spatialite libsqlite3-dev             libspatialite-dev &&     cd /srv/app &&     bundle install --full-index --without test development &&         chown -R www-data:www-data . &&         apt-get remove -y git build-essential zlib1g-dev gdal-bin             libsqlite3-dev libspatialite-dev &&     apt-get autoremove -y &&     apt-get clean &&     echo -n > /var/lib/apt/extended_states &&     rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*' returned a non-zero code: 18

**Comment by frodrigo** [comment]
I do not have the same behaviours.
Try this as Dockerfile to focus on the issue:
```
FROM mapotempo/nginx-passenger:2.0.1

LABEL maintainer="Mapotempo <contact@mapotempo.com>"

ENV RAILS_ENV production
ENV REDIS_HOST redis-cache

ADD . /srv/app

# Install app
RUN apt-get update
RUN    apt-get install -y git build-essential zlib1g-dev gdal-bin \
            zlib1g libsqlite3-mod-spatialite libsqlite3-dev \
            libspatialite-dev
RUN    cd /srv/app
RUN    bundle install --full-index --without test development

# Fix permissions
RUN    chown -R www-data:www-data .

# Cleanup Debian packages
RUN    apt-get remove -y git build-essential zlib1g-dev gdal-bin \
            libsqlite3-dev libspatialite-dev
RUN    apt-get autoremove -y
RUN    apt-get clean
RUN    echo -n > /var/lib/apt/extended_states
RUN    rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

ADD docker/env.d/* /etc/nginx/env.d/

VOLUME /srv/app/poly

WORKDIR /srv/app
```

**Comment by johnGarcia123** [comment]
ERROR: Service 'wrapper' failed to build: The command '/bin/sh -c bundle install --full-index --without test development' returned a non-zero code: 10

**Comment by johnGarcia123** [comment]
yes it runs fine without docker
